config/routes.rb
Tineetees::Application.routes.draw do
  #root page with navbar, products, footer
  root "welcome#index"

  #navbar: for customers logged in, allow them to edit their account info
  #get "/account/:id", to: "users#edit" #PJ: removing this, as it should, in REST, be below...

  #navbar: about page for website
  get "/about", to: "welcome#about"

  #navbar: sign in form
  get "/signin", to: "session#new"

  #navbar: contact submission form
  get "/contact", to: "welcome#contact"
  #post to contact, send email to admin
  post "/contact", to: "contact#create"

  #shopping cart for hipsters. the items in the basket are saved from session data
  #this function is still a little fuzzy because you need to be able to have the
  #items persistant after logging out
  #ask PJ
  get "/basket", to: "order#new"

  #checkout page after reviewing shopping cart where users who don't have accounts
  #can input their account info
  #and optionally create an account.
  #we may need to integrate with stripe
  #sends request to create an order after submitting (resource below)
  get "/checkout", to: "order#checkout"

  #info about completed order after it is created
  get "/confirmation", to: "order#read"

  resources :charges
  resources :shipments

  # Dashboard for admin.
  namespace :admin_dash do
    get "/", to: "users#admin" #if user signing in is an admin, they are redirected to this page.

    # A list of requests from Admin to Supplier of products to be manufactured.
    # Possible actions depends on whether Admin or Supplier are logged in...
    get "/supply_requests", to: "supply_requests#index"

    get "/products", to: "products#index"
    get "/orders", to: "order#index"
  end

  #supplier landing page
  get "/supplier", to: "users#supplier"

  put "/update_cart", to: "session#update_cart"

  #used to sign in/out AND hold info about shopping cart

  resources :session,         only: [:destroy, :create]

  resources :products,        only: [:update, :show, :edit, :destroy, :create]

  resources :supply_requests, only: [:create, :edit]
  resources :orders,          only: [:create]
  resources :users,           only: [:show, :edit]
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  include ActiveMerchant::Shipping

  validates :name, presence: true
  validates :country, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :postal_code, presence: true
  validates :length, presence: true
  validates :width, presence: true
  validates :height, presence: true
  validates :weight, presence: true
 
  def origin
    Location.new(country: "US", state: "NY", city: "Brooklyn", postal_code: "11221")
  end
 
  def destination
    Location.new(country: country, state: state, city: city, postal_code: postal_code)
  end
 
  def packages
    package = Package.new(weight, [length, width, height], cylinder: cylinder)
  end
 
  def get_rates_from_shipper(shipper)
    response = shipper.find_rates(origin, destination, packages)
    response.rates.sort_by(&:price)
  end
 
  # def ups_rates
  #   ups = UPS.new(login: 'your ups login', password: 'your ups password', key: 'your ups xml key')
  #   get_rates_from_shipper(ups)
  # end
 
  def fedex_rates
    fedex = FedEx.new(login: ENV['FEDEX_LOGIN'], 
                      password: ENV['FEDEX_PW'],
                      key: ENV['FEDEX_KEY'],
                      account: ENV['FEDEX_ACCOUNT_NUMBER'])
    get_rates_from_shipper(fedex)
  end
 
  # def usps_rates
  #   usps = USPS.new(login: 'your usps account number', password: 'your usps password')
  #   get_rates_from_shipper(usps)
  # end

end
 

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  def index
    @shipments = Shipment.all
  end
 
  def show
    @shipment = Shipment.find(params[:id])
  end
 
  def new
    @shipment = Shipment.new
  end
 
  def create
    @shipment = Shipment.new(shipment_params)
    if @shipment.save
      redirect_to @shipment, notice: "The shipment has been successfully created.  Below are your shipping options."
    else
      render action: "new"
    end
  end
 
  def edit
    @shipment = Shipment.find(params[:id])
  end
 
  def update
    @shipment = Shipment.find(params[:id])
    if @shipment.update_attributes(shipment_params)
      redirect_to @shipment, notice: "The shipment has been successfully updated.  Below are your shipping options."
    else
      render action: "edit"
    end
  end
 
private
 
  def shipment_params
    params.require(:shipment).permit(:name, :country, :city, :state, :postal_code, :length, :width, :height, :weight, :cylinder)
  end
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/shipments/_form.html.erb
<div>
For length, width, and height, use centimeters.  For weight, use grams.
</div>
 
<% if @shipment.errors.any? %>
  <ul>
    <%- @shipment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 
<%= form_for @shipment do |f| %>
  <div><%= f.label :name  %></div>
  <div><%= f.text_field :name %></div>
  <div><%= f.label :country %></div>
  <div><%= f.text_field :country %></div>
  <div><%= f.label :city %></div>
  <div><%= f.text_field :city %></div>
  <div><%= f.label :state %></div>
  <div><%= f.text_field :state %></div>
  <div><%= f.label :postal_code %></div>
  <div><%= f.text_field :postal_code %></div>
  <div><%= f.label :length %></div>
  <div><%= f.text_field :length %></div>
  <div><%= f.label :width %></div>
  <div><%= f.text_field :width %></div>
  <div><%= f.label :height %></div>
  <div><%= f.text_field :height %></div>
  <div><%= f.label :weight %></div>
  <div><%= f.text_field :weight %></div>
  <div>
    <%= f.check_box :cylinder %>
    <%= f.label :cylinder %>
  </div>
 
  <div><%= f.submit %></div>
<% end %>

app/views/shipments/edit.html.erb
<h3><%= "Editing Shipment for #{@shipment.name}" %></h3>
<%= render "form" %>

app/views/shipments/index.html.erb
<h3>Shipments</h3>
<%= link_to "New Shipment", new_shipment_path %>
<table style="width:100%; text-align:left;">
  <thead>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>Name</th>
    <th>Country</th>
    <th>City</th>
    <th>State</th>
    <th>Postal Code</th>
    <th>Length</th>
    <th>Width</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Cylinder?</th>
  </thead>
 
  <tbody>
    <% @shipments.each do |shipment| %>
      <tr>
        <td><%= link_to "View", shipment %></td>
        <td><%= link_to "Edit", edit_shipment_path(shipment) %></td>
        <td><%= shipment.name %></td>
        <td><%= shipment.country %></td>
        <td><%= shipment.city %></td>
        <td><%= shipment.state %></td>
        <td><%= shipment.postal_code %></td>
        <td><%= "#{shipment.length} centimeters" %></td>
        <td><%= "#{shipment.width} centimeters" %></td>
        <td><%= "#{shipment.height} centimeters" %></td>
        <td><%= "#{shipment.weight} grams" %></td>
        <td><%= shipment.cylinder ? "Yes" : "No" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shipments/new.html.erb
<h3>New Shipment</h3>
<%= render "form" %>

app/views/shipments/show.html.erb
<%= link_to "Edit shipment", edit_shipment_path(@shipment) %>&nbsp;|&nbsp;
<%= link_to "Back to Index", shipments_path %>
 
<h3>Shipping Information</h3>
<table style="width:100%; text-align:left;">
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
  </tr>
  <tr>
    <td><%= @shipment.name %></td>
    <td><%= @shipment.country %></td>
    <td><%= @shipment.city %></td>
    <td><%= @shipment.state %></td>
    <td><%= @shipment.postal_code %></td>
  </tr>
  <tr>
    <th>Length</th>
    <th>Width</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Cylinder?</th>
  </tr>
  <tr>
    <td><%= "#{@shipment.length} centimeters" %></td>
    <td><%= "#{@shipment.width} centimeters" %></td>
    <td><%= "#{@shipment.height} centimeters" %></td>
    <td><%= "#{@shipment.weight} grams" %></td>
    <td><%= @shipment.cylinder ? "Yes" : "No" %></td>
  </tr>
</table>
 
<h3>Shipping Options</h3>
<table>
  <tr>
    <th>Service Name</th>
    <th>Price</th>
  </tr>
  <% @shipment.ups_rates.each do |rate| %>
    <tr>
      <td><%= rate.service_name %></td>
      <td><%= number_to_currency(rate.price.to_f / 100) %></td>
    </tr>
  <% end %>
  <% @shipment.fedex_rates.each do |rate| %>
    <tr>
      <td><%= rate.service_name %></td>
      <td><%= number_to_currency(rate.price.to_f / 100) %></td>
    </tr>
  <% end %>
  <% @shipment.usps_rates.each do |rate| %>
    <tr>
      <td><%= rate.service_name %></td>
      <td><%= number_to_currency(rate.price.to_f / 100) %></td>
    </tr>
  <% end %>
</table>