config/routes.rb
Tineetees::Application.routes.draw do
  #root page with navbar, products, footer
  root "welcome#index"

  #navbar: for customers logged in, allow them to edit their account info
  #get "/account/:id", to: "users#edit" #PJ: removing this, as it should, in REST, be below...

  #navbar: about page for website
  get "/about", to: "welcome#about"

  #navbar: sign in form
  get "/signin", to: "session#new"

  #navbar: contact submission form
  get "/contact", to: "welcome#contact"
  #post to contact, send email to admin
  post "/contact", to: "contact#create"

  #shopping cart for hipsters. the items in the basket are saved from session data
  #this function is still a little fuzzy because you need to be able to have the
  #items persistant after logging out
  #ask PJ
  get "/basket", to: "order#new"

  #checkout page after reviewing shopping cart where users who don't have accounts
  #can input their account info
  #and optionally create an account.
  #we may need to integrate with stripe
  #sends request to create an order after submitting (resource below)
  get "/checkout", to: "order#checkout"

  #info about completed order after it is created
  get "/confirmation", to: "order#read"

  resources :charges
  resources :shipments

  # Dashboard for admin.
  namespace :admin_dash do
    get "/", to: "users#admin" #if user signing in is an admin, they are redirected to this page.

    # A list of requests from Admin to Supplier of products to be manufactured.
    # Possible actions depends on whether Admin or Supplier are logged in...
    get "/supply_requests", to: "supply_requests#index"

    get "/products", to: "products#index"
    get "/orders", to: "order#index"
  end

  #supplier landing page
  get "/supplier", to: "users#supplier"

  put "/update_cart", to: "session#update_cart"

  #used to sign in/out AND hold info about shopping cart

  resources :session,         only: [:destroy, :create]

  resources :products,        only: [:update, :show, :edit, :destroy, :create]

  resources :supply_requests, only: [:create, :edit]
  resources :orders,          only: [:create]
  resources :users,           only: [:show, :edit]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tineetees</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <section id="branding">
    <%= image_tag("tineetee1.jpg")%>
  </section>

  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Account", "/account/" %></li>
      <li><%= link_to "Cart", basket_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <% if logged_in? %>
        <li><%= link_to("Log Out", "/session", method: "delete") %></li>  
      <% else %>
        <li><%= link_to("Log In","/session") %></li>
      <% end %>
    </ul>
  </nav>
</header>

<%= yield %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

<footer>
  
</footer>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>